#!/bin/bash
#
# Script to remove signing information from a *.apk file.
#

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
. "${SCRIPT_DIR}/inc.functions.sh"

# Constants
CERT_FILES=(
    META-INF/CERT.RSA
    META-INF/CERT.SF
)

# Functions
function usage {
    echo -e "Usage: $0 [APK_OR_AAB]"
    exit 1
}

# Checks
if [[ $# -ne 1 ]] || ! test -f $1 ; then
    usage
fi

# Let's roll
for file in ${CERT_FILES[@]} ; do
    zip -d "$1" "${file}"
done
